# IC Light v2 Professional - Database Examples
# Professional dataset for IC Light demonstrations and quick prompts

# Text-Conditioned Model Examples
foreground_conditioned_examples = [
    [
        "imgs/i1.webp",
        "beautiful woman, detailed face, sunshine, outdoor, warm atmosphere",
        "Right Light",
        512,
        960,
        12345,
        "imgs/o1.png",
    ],
    [
        "imgs/i1.webp",
        "beautiful woman, detailed face, sunshine, outdoor, warm atmosphere",
        "Left Light",
        512,
        960,
        50,
        "imgs/o2.png",
    ],
    [
        "imgs/i3.png",
        "beautiful woman, detailed face, neon, Wong Kar-wai, warm",
        "Left Light",
        512,
        768,
        12345,
        "imgs/o3.png",
    ],
    [
        "imgs/i3.png",
        "beautiful woman, detailed face, sunshine from window",
        "Left Light",
        512,
        768,
        12345,
        "imgs/o4.png",
    ],
    [
        "imgs/i5.png",
        "beautiful woman, detailed face, warm atmosphere, at home, bedroom",
        "Left Light",
        512,
        768,
        123,
        "imgs/o5.png",
    ],
    [
        "imgs/i6.jpg",
        "beautiful woman, detailed face, sunshine from window",
        "Right Light",
        512,
        768,
        42,
        "imgs/o6.png",
    ],
    [
        "imgs/i7.jpg",
        "beautiful woman, detailed face, shadow from window",
        "Left Light",
        512,
        768,
        8888,
        "imgs/o7.png",
    ],
    [
        "imgs/i8.webp",
        "beautiful woman, detailed face, sunset over sea",
        "Right Light",
        512,
        640,
        42,
        "imgs/o8.png",
    ],
    [
        "imgs/i9.png",
        "handsome boy, detailed face, neon light, city",
        "Left Light",
        512,
        640,
        12345,
        "imgs/o9.png",
    ],
    [
        "imgs/i10.png",
        "beautiful woman, detailed face, light and shadow",
        "Left Light",
        512,
        960,
        8888,
        "imgs/o10.png",
    ],
    [
        "imgs/i11.png",
        "Buddha, detailed face, sci-fi RGB glowing, cyberpunk",
        "Left Light",
        512,
        768,
        8888,
        "imgs/o11.png",
    ],
    [
        "imgs/i11.png",
        "Buddha, detailed face, natural lighting",
        "Left Light",
        512,
        768,
        12345,
        "imgs/o12.png",
    ],
    [
        "imgs/i13.png",
        "toy, detailed face, shadow from window",
        "Bottom Light",
        512,
        704,
        12345,
        "imgs/o13.png",
    ],
    [
        "imgs/i14.png",
        "toy, detailed face, sunset over sea",
        "Right Light",
        512,
        704,
        100,
        "imgs/o14.png",
    ],
    [
        "imgs/i15.png",
        "dog, magic lit, sci-fi RGB glowing, studio lighting",
        "Bottom Light",
        512,
        768,
        12345,
        "imgs/o15.png",
    ],
    [
        "imgs/i16.png",
        "mysteriou human, warm atmosphere, warm atmosphere, at home, bedroom",
        "Right Light",
        512,
        768,
        100,
        "imgs/o16.png",
    ],
]

# Background Image Gallery for Quick Selection
bg_samples = [
    'imgs/bgs/1.webp',
    'imgs/bgs/2.webp',
    'imgs/bgs/3.webp',
    'imgs/bgs/4.webp',
    'imgs/bgs/5.webp',
    'imgs/bgs/6.webp',
    'imgs/bgs/7.webp',
    'imgs/bgs/8.webp',
    'imgs/bgs/9.webp',
    'imgs/bgs/10.webp',
    'imgs/bgs/11.png',
    'imgs/bgs/12.png',
    'imgs/bgs/13.png',
    'imgs/bgs/14.png',
    'imgs/bgs/15.png',
]

# Background-Conditioned Model Examples
background_conditioned_examples = [
    [
        "imgs/alter/i3.png",
        "imgs/bgs/7.webp",
        "beautiful woman, cinematic lighting",
        "Use Background Image",
        512,
        768,
        12345,
        "imgs/alter/o1.png",
    ],
    [
        "imgs/alter/i2.png",
        "imgs/bgs/11.png",
        "statue of an angel, natural lighting",
        "Use Flipped Background Image",
        512,
        768,
        12345,
        "imgs/alter/o2.png",
    ],
    [
        "imgs/alter/i1.jpeg",
        "imgs/bgs/2.webp",
        "beautiful woman, cinematic lighting",
        "Use Background Image",
        512,
        768,
        12345,
        "imgs/alter/o3.png",
    ],
    [
        "imgs/alter/i1.jpeg",
        "imgs/bgs/3.webp",
        "beautiful woman, cinematic lighting",
        "Use Background Image",
        512,
        768,
        12345,
        "imgs/alter/o4.png",
    ],
    [
        "imgs/alter/i6.webp",
        "imgs/bgs/15.png",
        "handsome man, cinematic lighting",
        "Use Background Image",
        512,
        768,
        12345,
        "imgs/alter/o5.png",
    ],
]

# Professional Lighting Quick Prompts
quick_lighting_prompts = [
    "sunshine from window",
    "shadow from window", 
    "neon light, city",
    "sunset over sea",
    "warm atmosphere, at home",
    "sci-fi RGB glowing",
    "natural lighting",
    "studio lighting",
    "cinematic lighting",
    "magic lit",
    "soft lighting",
    "dramatic lighting",
    "golden hour",
    "blue hour",
    "candlelight",
    "fireplace glow",
    "moonlight",
    "street lighting",
    "stage lighting",
    "rim lighting",
    "backlighting",
    "side lighting",
    "top lighting",
    "bottom lighting",
    "diffused lighting"
]

# Professional Subject Quick Prompts  
quick_subject_prompts = [
    "beautiful woman, detailed face",
    "handsome man, detailed face", 
    "elderly person, wise expression",
    "child, innocent smile",
    "businessman, professional attire",
    "artist, creative expression",
    "athlete, dynamic pose",
    "dancer, graceful movement",
    "musician, passionate performance",
    "chef, culinary expertise",
    "doctor, caring demeanor",
    "teacher, knowledgeable look",
    "fashion model, elegant pose",
    "portrait, photorealistic",
    "headshot, professional",
    "full body, confident stance"
]

# Professional Style Quick Prompts
quick_style_prompts = [
    "photorealistic, high quality",
    "cinematic style, film grain",
    "portrait photography, 85mm lens",
    "studio photography, clean background",
    "fashion photography, editorial style",
    "fine art photography, artistic vision",
    "commercial photography, polished look",
    "street photography, candid moment",
    "vintage style, film photography",
    "modern style, contemporary look",
    "classic style, timeless beauty",
    "artistic style, creative expression",
    "documentary style, authentic feel",
    "glamour photography, sophisticated",
    "lifestyle photography, natural",
    "corporate photography, professional"
]

# Combined Quick Prompts for Easy Access
quick_prompts = [
    # Lighting combinations
    "sunshine from window, warm atmosphere",
    "shadow from window, dramatic mood", 
    "neon light, city, cyberpunk style",
    "sunset over sea, golden hour",
    "natural lighting, outdoor setting",
    "studio lighting, professional setup",
    "cinematic lighting, film style",
    "soft lighting, gentle mood",
    "dramatic lighting, high contrast",
    "golden hour, warm tones",
    "blue hour, cool tones",
    "candlelight, intimate atmosphere",
    "fireplace glow, cozy setting",
    "moonlight, mysterious mood",
    "street lighting, urban night",
    
    # Advanced lighting techniques
    "rim lighting, dramatic silhouette",
    "backlighting, ethereal glow",
    "side lighting, sculptural form",
    "top lighting, classic portrait",
    "bottom lighting, dramatic effect",
    "diffused lighting, soft shadows",
    "hard lighting, sharp shadows",
    "ambient lighting, natural feel",
    "accent lighting, focused highlight",
    "fill lighting, balanced exposure"
]
