"""
Base classes for AI Dev Collective agents
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Any, Optional
from dataclasses import dataclass, field
from datetime import datetime
import json


@dataclass
class AgentReport:
    """Report generated by an agent"""
    agent_name: str
    role: str
    timestamp: str
    findings: List[str] = field(default_factory=list)
    recommendations: List[str] = field(default_factory=list)
    metrics: Dict[str, Any] = field(default_factory=dict)
    priority: str = "medium"  # low, medium, high, critical
    
    def to_dict(self) -> Dict:
        """Convert report to dictionary"""
        return {
            "agent_name": self.agent_name,
            "role": self.role,
            "timestamp": self.timestamp,
            "findings": self.findings,
            "recommendations": self.recommendations,
            "metrics": self.metrics,
            "priority": self.priority
        }
    
    def to_json(self) -> str:
        """Convert report to JSON string"""
        return json.dumps(self.to_dict(), indent=2)


class Agent(ABC):
    """Base class for all agents in the AI Dev Collective"""
    
    def __init__(self, name: str, role: str, responsibilities: List[str]):
        self.name = name
        self.role = role
        self.responsibilities = responsibilities
        self.reports: List[AgentReport] = []
        
    @abstractmethod
    def analyze(self, project_path: str) -> AgentReport:
        """Analyze the software project and generate a report"""
        pass
    
    def get_latest_report(self) -> Optional[AgentReport]:
        """Get the most recent report"""
        return self.reports[-1] if self.reports else None
    
    def get_all_reports(self) -> List[AgentReport]:
        """Get all reports generated by this agent"""
        return self.reports
    
    def __str__(self) -> str:
        return f"{self.name} ({self.role})"


class AgentTeam:
    """Manages a team of AI agents for software analysis"""
    
    def __init__(self, name: str, description: str):
        self.name = name
        self.description = description
        self.members: List[Agent] = []
        self.analysis_results: Dict[str, AgentReport] = {}
        
    def add_member(self, agent: Agent):
        """Add an agent to the team"""
        self.members.append(agent)
        
    def run_analysis(self, project_path: str, agents: Optional[List[str]] = None) -> Dict[str, AgentReport]:
        """
        Run analysis with all agents or specified agents
        
        Args:
            project_path: Path to the software project
            agents: List of agent names to run (None = all agents)
            
        Returns:
            Dictionary mapping agent names to their reports
        """
        results = {}
        
        for agent in self.members:
            # Skip if specific agents requested and this isn't one
            if agents and agent.name not in agents:
                continue
                
            print(f"🔍 Running analysis with {agent}...")
            try:
                report = agent.analyze(project_path)
                agent.reports.append(report)
                results[agent.name] = report
                print(f"✅ {agent.name} analysis complete")
            except Exception as e:
                print(f"❌ {agent.name} analysis failed: {e}")
                
        self.analysis_results = results
        return results
    
    def generate_summary_report(self) -> Dict[str, Any]:
        """Generate a summary report from all agent analyses"""
        if not self.analysis_results:
            return {"error": "No analysis results available"}
        
        summary = {
            "team": self.name,
            "description": self.description,
            "timestamp": datetime.now().isoformat(),
            "total_agents": len(self.members),
            "analyzed_by": len(self.analysis_results),
            "agents": []
        }
        
        all_findings = []
        all_recommendations = []
        critical_issues = []
        
        for agent_name, report in self.analysis_results.items():
            summary["agents"].append({
                "name": agent_name,
                "role": report.role,
                "findings_count": len(report.findings),
                "recommendations_count": len(report.recommendations),
                "priority": report.priority
            })
            
            all_findings.extend(report.findings)
            all_recommendations.extend(report.recommendations)
            
            if report.priority == "critical":
                critical_issues.extend(report.findings)
        
        summary["total_findings"] = len(all_findings)
        summary["total_recommendations"] = len(all_recommendations)
        summary["critical_issues_count"] = len(critical_issues)
        summary["critical_issues"] = critical_issues
        
        return summary
    
    def export_reports(self, output_path: str, format: str = "json"):
        """
        Export all reports to file
        
        Args:
            output_path: Path to output file
            format: Output format (json, markdown)
        """
        if format == "json":
            data = {
                "team": self.name,
                "description": self.description,
                "timestamp": datetime.now().isoformat(),
                "reports": [report.to_dict() for report in self.analysis_results.values()]
            }
            with open(output_path, 'w') as f:
                json.dumps(data, f, indent=2)
                
        elif format == "markdown":
            with open(output_path, 'w') as f:
                f.write(f"# {self.name}\n\n")
                f.write(f"{self.description}\n\n")
                f.write(f"**Generated:** {datetime.now().isoformat()}\n\n")
                f.write("---\n\n")
                
                for agent_name, report in self.analysis_results.items():
                    f.write(f"## {agent_name} - {report.role}\n\n")
                    
                    if report.findings:
                        f.write("### 🔍 Findings\n\n")
                        for finding in report.findings:
                            f.write(f"- {finding}\n")
                        f.write("\n")
                    
                    if report.recommendations:
                        f.write("### 💡 Recommendations\n\n")
                        for rec in report.recommendations:
                            f.write(f"- {rec}\n")
                        f.write("\n")
                    
                    if report.metrics:
                        f.write("### 📊 Metrics\n\n")
                        for key, value in report.metrics.items():
                            f.write(f"- **{key}:** {value}\n")
                        f.write("\n")
                    
                    f.write("---\n\n")
    
    def __str__(self) -> str:
        return f"{self.name} ({len(self.members)} members)"
